apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  name: simple
  labels:
    app.kubernetes.io/instance: ham-deployable-operator
    app.kubernetes.io/managed-by: ham-deployable-operator
    app.kubernetes.io/name: hybridApplicationModel
spec:
  templates:
  - deployerType: cloudform
    template:
      apiVersion: multicloud-apps.io/v1alpha1
      kind: Subscription
      metadata:
        name: cloudform-sub
        spec:
          channel: ch-cfrepo/channel
